// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {backend} from '../models';

export function ClearAvatar():Promise<store.User>;

export function CurrentUser():Promise<store.User>;

export function GeocodeSearch(arg1:string):Promise<Array<backend.GeocodeResult>>;

export function GetPreferences():Promise<store.Preferences>;

export function ListEmbeddedAreas():Promise<Array<backend.Area>>;

export function ListRuns(arg1:number):Promise<Array<store.InferenceRun>>;

export function Login(arg1:string,arg2:string):Promise<store.User>;

export function Logout():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function Predict(arg1:backend.PredictRequest):Promise<backend.PredictResult>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<store.User>;

export function SavePreferences(arg1:store.Preferences):Promise<void>;

export function SetAvatar(arg1:string):Promise<store.User>;

export function UpdateProfile(arg1:string):Promise<store.User>;
