// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeocodeSearch(arg1) {
  return window['go']['main']['App']['GeocodeSearch'](arg1);
}

export function ListEmbeddedAreas() {
  return window['go']['main']['App']['ListEmbeddedAreas']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function Predict(arg1) {
  return window['go']['main']['App']['Predict'](arg1);
}
