// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GeocodeSearch(arg1:string):Promise<Array<backend.GeocodeResult>>;

export function ListEmbeddedAreas():Promise<Array<backend.Area>>;

export function OpenExternal(arg1:string):Promise<void>;

export function Predict(arg1:backend.PredictRequest):Promise<backend.PredictResult>;
