// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAvatar() {
  return window['go']['main']['App']['ClearAvatar']();
}

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function GeocodeSearch(arg1) {
  return window['go']['main']['App']['GeocodeSearch'](arg1);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function ListEmbeddedAreas() {
  return window['go']['main']['App']['ListEmbeddedAreas']();
}

export function ListRuns(arg1) {
  return window['go']['main']['App']['ListRuns'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function Predict(arg1) {
  return window['go']['main']['App']['Predict'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SetAvatar(arg1) {
  return window['go']['main']['App']['SetAvatar'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
